In [1]:
# Numerical and scientific python programming
import numpy as np

# Local importations
from moments.bloch import generate_pauli_basis, compute_tensor_basis, compute_subset_index_map, compute_bloch_vector
from moments.ent_meas import compute_negativity

In [2]:
phi_0 = np.array([[1], [0]])
phi_1 = np.array([[0], [1]])

psi = (1 / np.sqrt(2)) * (np.kron(phi_0, phi_0) + np.kron(phi_1, phi_1))

print(psi)

rho = np.kron(psi, np.conj(psi).T)

print(rho)

[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]
[[0.5 0.  0.  0.5]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.5 0.  0.  0.5]]


In [3]:
N_max = compute_negativity(rho)

print("Maximum negativity for two-qubits:", N_max)

Maximum negativity for two-qubits: 0.4999999999999998


In [4]:
dn, N = 2, 2

pauli_basis = generate_pauli_basis()

local_bases = [pauli_basis.copy()] * N
local_basis_sizes = [len(basis) for basis in local_bases]

tensor_basis = compute_tensor_basis(local_bases)
subset_index_map = compute_subset_index_map(local_basis_sizes)

r = compute_bloch_vector(tensor_basis, subset_index_map, rho)
print(r)

{(1,): array([0., 0., 0.]), (2,): array([0., 0., 0.]), (1, 2): array([ 1.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  1.])}
