# Importations

In [1]:
import numpy as np
from bisep_computer import biseparable_state

# Definitions

In [2]:
phi_0 = np.array([1, 0]).reshape(2, 1)
phi_1 = np.array([0, 1]).reshape(2, 1)

phi_00 = np.kron(phi_0, phi_0)
phi_11 = np.kron(phi_1, phi_1)

In [3]:
p = np.array([1/3]*3)
q_A = q_B = q_C= np.array([0.5]*2)

In [4]:
psiA_1 = psiB_1 = 0.5 * (- np.sqrt(3) * phi_0 + phi_1)
psiA_2 = psiB_2 = 0.5 * (np.sqrt(3) * phi_0 + phi_1)

psiBC_1 = psiAC_1 = 0.5 * (np.sqrt(3) * phi_00 + phi_11)
psiBC_2 = psiAC_2 = 0.5 * (- np.sqrt(3) * phi_00 + phi_11)

psiC_1 = 0.5 * (- np.sqrt(3) * 1j * phi_0 + phi_1)
psiC_2 = 0.5 * (np.sqrt(3) * 1j * phi_0 + phi_1)

psiAB_1 = 0.5 * (- np.sqrt(3) * 1j * phi_00 + phi_11)
psiAB_2 = 0.5 * (np.sqrt(3) * 1j * phi_00 + phi_11)

PSI_A = PSI_B = [psiA_1, psiA_2]
PSI_C = [psiC_1, psiC_2]

PSI_BC = PSI_AC = [psiAC_1, psiAC_2]
PSI_AB = [psiAB_1, psiAB_2]

In [5]:
print("Subsystem A:")
print("\n- A:")
for psi_a in PSI_A:
    print(np.round(psi_a, 2))

print("\n- BC:")
for psi_bc in PSI_BC:
    print(np.round(psi_bc, 2))

print("\nSubsystem B:")
print("\n- B:")
for psi_b in PSI_B:
    print(np.round(psi_b, 2))

print("\n- AC:")
for psi_ac in PSI_AC:
    print(np.round(psi_ac, 2))

print("\nSubsystem C:")
print("\n- C:")
for psi_c in PSI_C:
    print(np.round(psi_c, 2))

print("\n- BC:")
for psi_ab in PSI_AB:
    print(np.round(psi_ab, 2))

Subsystem A:

- A:
[[-0.87]
 [ 0.5 ]]
[[0.87]
 [0.5 ]]

- BC:
[[0.87]
 [0.  ]
 [0.  ]
 [0.5 ]]
[[-0.87]
 [ 0.  ]
 [ 0.  ]
 [ 0.5 ]]

Subsystem B:

- B:
[[-0.87]
 [ 0.5 ]]
[[0.87]
 [0.5 ]]

- AC:
[[0.87]
 [0.  ]
 [0.  ]
 [0.5 ]]
[[-0.87]
 [ 0.  ]
 [ 0.  ]
 [ 0.5 ]]

Subsystem C:

- C:
[[0. -0.87j]
 [0.5+0.j  ]]
[[0. +0.87j]
 [0.5+0.j  ]]

- BC:
[[0. -0.87j]
 [0. +0.j  ]
 [0. +0.j  ]
 [0.5+0.j  ]]
[[0. +0.87j]
 [0. +0.j  ]
 [0. +0.j  ]
 [0.5+0.j  ]]


# Compute state

In [6]:
rho = biseparable_state(p,
                        PSI_A, q_A, PSI_BC,
                        PSI_B, q_B, PSI_AC,
                        PSI_C, q_C, PSI_AB)

In [7]:
print(rho.real)

[[ 0.5625  0.      0.      0.      0.      0.      0.     -0.1875]
 [ 0.      0.0625  0.      0.      0.      0.      0.0625  0.    ]
 [ 0.      0.      0.0625  0.      0.     -0.0625  0.      0.    ]
 [ 0.      0.      0.      0.0625 -0.0625  0.      0.      0.    ]
 [ 0.      0.      0.     -0.0625  0.0625  0.      0.      0.    ]
 [ 0.      0.     -0.0625  0.      0.      0.0625  0.      0.    ]
 [ 0.      0.0625  0.      0.      0.      0.      0.0625  0.    ]
 [-0.1875  0.      0.      0.      0.      0.      0.      0.0625]]
