# Importations

In [1]:
import numpy as np
from bisep_finder import ClosestBiSeparableFinder, print_decomposition, reconstruct_state_from_decomposition

# Decomposing

In [2]:
rho_target = (1/16) * np.array([[9,  0,  0,  0,  0,  0,  0, -3],
                                [0,  1,  0,  0,  0,  0,  1,  0],
                                [0,  0,  1,  0,  0, -1,  0,  0],
                                [0,  0,  0,  1, -1,  0,  0,  0],
                                [0,  0,  0, -1,  1,  0,  0,  0],
                                [0,  0, -1,  0,  0,  1,  0,  0],
                                [0,  1,  0,  0,  0,  0,  1,  0],
                                [-3, 0,  0,  0,  0,  0,  0,  1]])

In [3]:
print("Finding closest bi-separable state...")
optimizer = ClosestBiSeparableFinder(rho_target, decomposition_length=2, method='SLSQP')
result = optimizer.optimize(n_restarts=5, max_iter=300)

Finding closest bi-separable state...
Restart 1/5
  Distance: 2.050637e-08, Success: True
Restart 2/5
  Distance: 5.601598e-03, Success: True
Restart 3/5
  Distance: 1.099446e-09, Success: True
Restart 4/5
  Distance: 5.601584e-03, Success: True
Restart 5/5
  Distance: 5.650737e-03, Success: True


In [4]:
# Access results
rho_bi_sep = result['rho_bi_separable']
distance = result['distance']
print(f"Frobenius distance: {np.sqrt(distance):.6f}")
print(f"Trace distance: {0.5 * np.sum(np.abs(np.linalg.eigvalsh(rho_target - rho_bi_sep))):.6f}")

Frobenius distance: 0.000033
Trace distance: 0.000033


In [5]:
print(rho_target)

[[ 0.5625  0.      0.      0.      0.      0.      0.     -0.1875]
 [ 0.      0.0625  0.      0.      0.      0.      0.0625  0.    ]
 [ 0.      0.      0.0625  0.      0.     -0.0625  0.      0.    ]
 [ 0.      0.      0.      0.0625 -0.0625  0.      0.      0.    ]
 [ 0.      0.      0.     -0.0625  0.0625  0.      0.      0.    ]
 [ 0.      0.     -0.0625  0.      0.      0.0625  0.      0.    ]
 [ 0.      0.0625  0.      0.      0.      0.      0.0625  0.    ]
 [-0.1875  0.      0.      0.      0.      0.      0.      0.0625]]


In [6]:
print(rho_bi_sep)

[[ 5.62486585e-01-4.45638008e-18j -1.88060709e-07-4.49207255e-07j
  -9.56890698e-07-2.81501078e-06j -1.07550506e-06-2.04846728e-07j
  -8.48932814e-08+9.11164380e-07j -3.49604444e-07-1.71871877e-06j
  -5.46715077e-07-6.65485867e-07j -1.87486116e-01+4.27884512e-07j]
 [-1.88060709e-07+4.49207255e-07j  6.24995797e-02+1.51156630e-19j
  -1.31397127e-06+1.51647872e-06j  8.23597751e-07+8.82703506e-07j
  -7.83532887e-07-3.68233125e-07j  3.26280672e-06+2.21537045e-06j
   6.24986641e-02-2.56274392e-07j -3.96936339e-07+1.30130751e-06j]
 [-9.56890698e-07+2.81501078e-06j -1.31397127e-06-1.51647872e-06j
   6.25063128e-02-5.77691767e-19j  2.14152422e-07+3.43426605e-08j
   1.80235984e-06+3.61166650e-07j -6.24903606e-02-8.29874726e-07j
  -1.52673205e-07-5.25428566e-08j  2.46263071e-08+3.67439863e-06j]
 [-1.07550506e-06+2.04846728e-07j  8.23597751e-07-8.82703506e-07j
   2.14152422e-07-3.43426605e-08j  6.24993888e-02+3.04078497e-19j
  -6.24981383e-02+2.36246355e-07j  1.29047041e-06+8.64885755e-08j
  -7.31

In [7]:
print(np.round(rho_bi_sep, decimals=4).real)

[[ 0.5625 -0.     -0.     -0.     -0.     -0.     -0.     -0.1875]
 [-0.      0.0625 -0.      0.     -0.      0.      0.0625 -0.    ]
 [-0.     -0.      0.0625  0.      0.     -0.0625 -0.      0.    ]
 [-0.      0.      0.      0.0625 -0.0625  0.     -0.     -0.    ]
 [-0.     -0.      0.     -0.0625  0.0625  0.      0.     -0.    ]
 [-0.      0.     -0.0625  0.      0.      0.0625 -0.     -0.    ]
 [-0.      0.0625 -0.     -0.      0.     -0.      0.0625  0.    ]
 [-0.1875 -0.      0.     -0.     -0.     -0.      0.      0.0625]]


In [8]:
# Print the decomposition
print_decomposition(result['decomposition'])


BI-SEPARABLE DECOMPOSITION

Partition mixture weights:
  A|BC: 0.3316
  B|AC: 0.3331
  C|AB: 0.3353

Sum of partition weights: 1.000000

----------------------------------------
Partition: A|BC (total weight: 0.3316)
Number of terms: 2

  Term 1: weight = 0.4993
    |ψ_A⟩ = [-0.0443-0.8644j  0.026 +0.5002j]
    |ψ_BC⟩ = [-0.864 -0.0213j  0.0017-0.0007j -0.0033+0.0036j -0.5029-0.012j ]

  Term 2: weight = 0.5007
    |ψ_A⟩ = [0.281 -0.8173j 0.1632-0.4759j]
    |ψ_BC⟩ = [-7.556e-01+0.4221j -3.000e-04+0.0034j -1.400e-03+0.0036j
  4.371e-01-0.2445j]

  Sum of term weights: 1.000000

----------------------------------------
Partition: B|AC (total weight: 0.3331)
Number of terms: 2

  Term 1: weight = 0.4979
    |ψ_B⟩ = [0.856 -0.1419j 0.4903-0.0821j]
    |ψ_AC⟩ = [ 4.252e-01+7.522e-01j  1.000e-04-1.000e-03j -1.700e-03-2.000e-04j
 -2.484e-01-4.378e-01j]

  Term 2: weight = 0.5021
    |ψ_B⟩ = [-0.1635+0.8485j  0.0945-0.4944j]
    |ψ_AC⟩ = [-0.755 -4.276e-01j -0.0011+1.000e-03j  0.0011+4.000e-

In [9]:
# Verify reconstruction
print("\n" + "="*60)
print("VERIFICATION")
print("="*60)
rho_reconstructed = reconstruct_state_from_decomposition(result['decomposition'])
print(f"Reconstruction error: {np.linalg.norm(result['rho_bi_separable'] - rho_reconstructed):.2e}")
print(f"Distance to target: {np.sqrt(result['distance']):.6f}")


VERIFICATION
Reconstruction error: 5.70e-17
Distance to target: 0.000033
