# Importations

In [ ]:
import numpy as np
from bisep_finder import ClosestBiSeparableFinder, print_decomposition, reconstruct_state_from_decomposition

# Decomposing

In [2]:
rho_target = (1/16) * np.array([[9,  0,  0,  0,  0,  0,  0, -3],
                                [0,  1,  0,  0,  0,  0,  1,  0],
                                [0,  0,  1,  0,  0, -1,  0,  0],
                                [0,  0,  0,  1, -1,  0,  0,  0],
                                [0,  0,  0, -1,  1,  0,  0,  0],
                                [0,  0, -1,  0,  0,  1,  0,  0],
                                [0,  1,  0,  0,  0,  0,  1,  0],
                                [-3, 0,  0,  0,  0,  0,  0,  1]])

In [3]:
print("Finding closest bi-separable state...")
optimizer = ClosestBiSeparableFinder(rho_target, decomposition_length=2, method='SLSQP')
result = optimizer.optimize(n_restarts=5, max_iter=300)

Finding closest bi-separable state...
Restart 1/5
  Distance: 3.318345e-09, Success: True
Restart 2/5
  Distance: 1.667196e-09, Success: True
Restart 3/5
  Distance: 5.988660e-09, Success: True
Restart 4/5
  Distance: 5.969738e-09, Success: True
Restart 5/5
  Distance: 5.601648e-03, Success: True


In [4]:
# Access results
rho_bi_sep = result['rho_bi_separable']
distance = result['distance']
print(f"Frobenius distance: {np.sqrt(distance):.6f}")
print(f"Trace distance: {0.5 * np.sum(np.abs(np.linalg.eigvalsh(rho_target - rho_bi_sep))):.6f}")

Frobenius distance: 0.000041
Trace distance: 0.000042


In [5]:
print(rho_target)

[[ 0.5625  0.      0.      0.      0.      0.      0.     -0.1875]
 [ 0.      0.0625  0.      0.      0.      0.      0.0625  0.    ]
 [ 0.      0.      0.0625  0.      0.     -0.0625  0.      0.    ]
 [ 0.      0.      0.      0.0625 -0.0625  0.      0.      0.    ]
 [ 0.      0.      0.     -0.0625  0.0625  0.      0.      0.    ]
 [ 0.      0.     -0.0625  0.      0.      0.0625  0.      0.    ]
 [ 0.      0.0625  0.      0.      0.      0.      0.0625  0.    ]
 [-0.1875  0.      0.      0.      0.      0.      0.      0.0625]]


In [6]:
print(rho_bi_sep)

[[ 5.62487699e-01+8.49335557e-19j -3.17832177e-06-1.03676804e-06j
   1.28570673e-06-7.86358663e-07j  1.57547354e-06-5.75654319e-10j
   9.34805343e-07+1.19779972e-06j -9.23563629e-07-9.07507775e-07j
   1.64526593e-06-5.58039599e-07j -1.87479758e-01-1.26211980e-07j]
 [-3.17832177e-06+1.03676804e-06j  6.24994635e-02-3.34366314e-19j
   7.20444527e-07-8.13218655e-07j -1.42626312e-07+4.36483098e-06j
   1.09908909e-06+4.43199968e-07j -1.69393693e-06+1.85919489e-07j
   6.24958144e-02-4.64192472e-07j -2.76403928e-06+1.52287609e-06j]
 [ 1.28570673e-06+7.86358663e-07j  7.20444527e-07+8.13218655e-07j
   6.24976914e-02+3.74028535e-19j  2.82110297e-06+1.32157701e-06j
   1.74893148e-06+1.05003795e-06j -6.24973267e-02+8.82962362e-07j
  -2.17221242e-07-8.48907793e-07j -7.56182045e-07+8.59957707e-07j]
 [ 1.57547354e-06+5.75654316e-10j -1.42626312e-07-4.36483098e-06j
   2.82110297e-06-1.32157701e-06j  6.25021845e-02+1.04045384e-18j
  -6.24926233e-02-6.23276226e-07j -3.21654641e-06-4.92294211e-08j
   8.68

In [7]:
print(np.round(rho_bi_sep, decimals=4).real)

[[ 0.5625 -0.      0.      0.      0.     -0.      0.     -0.1875]
 [-0.      0.0625  0.     -0.      0.     -0.      0.0625 -0.    ]
 [ 0.      0.      0.0625  0.      0.     -0.0625 -0.     -0.    ]
 [ 0.     -0.      0.      0.0625 -0.0625 -0.      0.      0.    ]
 [ 0.      0.      0.     -0.0625  0.0625 -0.     -0.      0.    ]
 [-0.     -0.     -0.0625 -0.     -0.      0.0625 -0.     -0.    ]
 [ 0.      0.0625 -0.      0.     -0.     -0.      0.0625  0.    ]
 [-0.1875 -0.     -0.      0.      0.     -0.      0.      0.0625]]


In [8]:
# Print the decomposition
print_decomposition(result['decomposition'])


BI-SEPARABLE DECOMPOSITION

Partition mixture weights:
  A|BC: 0.3375
  B|AC: 0.3316
  C|AB: 0.3310

Sum of partition weights: 1.000000

----------------------------------------
Partition: A|BC (total weight: 0.3375)
Number of terms: 2

  Term 1: weight = 0.4995
    |ψ_A⟩ = [-0.1011-0.8632j  0.0592+0.4911j]
    |ψ_BC⟩ = [-0.8641+0.0855j  0.0026+0.0003j  0.0021+0.j     -0.4935+0.0505j]

  Term 2: weight = 0.5005
    |ψ_A⟩ = [-0.7536-0.4312j -0.4314-0.2449j]
    |ψ_BC⟩ = [ 0.3889-0.7771j -0.0019+0.0025j  0.0008-0.0008j -0.2199+0.4432j]

  Sum of term weights: 1.000000

----------------------------------------
Partition: B|AC (total weight: 0.3316)
Number of terms: 2

  Term 1: weight = 0.4997
    |ψ_B⟩ = [ 0.0867-0.8608j -0.053 +0.4987j]
    |ψ_AC⟩ = [ 0.1802-0.8456j  0.0028-0.0027j -0.0047-0.002j   0.1075-0.4909j]

  Term 2: weight = 0.5003
    |ψ_B⟩ = [0.1029+0.8584j 0.057 +0.4993j]
    |ψ_AC⟩ = [-0.8633-0.0563j -0.0027+0.0031j  0.002 +0.0046j  0.5002+0.0354j]

  Sum of term weights: 

In [10]:
# Verify reconstruction
print("\n" + "="*60)
print("VERIFICATION")
print("="*60)
rho_reconstructed = reconstruct_state_from_decomposition(result['decomposition'])
print(f"Reconstruction error: {np.linalg.norm(result['rho_bi_separable'] - rho_reconstructed):.2e}")
print(f"Distance to target: {np.sqrt(result['distance']):.6f}")


VERIFICATION
Reconstruction error: 4.50e-17
Distance to target: 0.000041
